'use strict';const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const scope={};for(const f of ['norma','flexao','entrada-flexao','verificacao-flexao','cisalhamento','verificacao-cisalhamento','resumo-horizontal'])new Function('globalThis',fs.readFileSync(path.join(__dirname,'../js',f+'.js'),'utf8'))(scope);
const {Flexao:F,VerificacaoFlexao:V,ResumoHorizontal:R,VerificacaoCisalhamento:C}=scope.FS;
const base={fck:30,fyk:500,tipoAco:'A',gammaC:1.4,gammaS:1.15,gammaF:1.4,secao:'RET',bw:100,d:15,dl:5,h:20,Msd:2.65,As:F.areaBarras(10,8),Asl:0,betaXLim:.45,usarArmaduraMinima:true,armaduraDupla:true};
const op={unidade:'kgfm',elemento:'BLOCO SP-01',norma:'2023',modoAs:'barras',nBarras:10,diamBarras:8};
const clean=s=>s.replace(/<[^>]*>/g,'');
const linhas=s=>s.replace(/<\/text>/g,'\n').replace(/<[^>]*>/g,'');
test('RV08: reproduz D/C, FS e valores do caso enviado no resumo em três painéis',()=>{let q=V.verificar(base),s=R.flexao(q,op),t=clean(s);assert.ok(t.includes('0,84'));assert.ok(t.includes('1,19'));assert.ok(t.includes('3.147,07'));assert.ok(t.includes('kgf·m'));for(let field of ['fck','fyk','bw','h =','d =','d′','As,mín','As,máx','As,adotada','Msk','MSd','MRd','D/C','FS','Seção transversal','Diagrama','Verificações da seção','Conclusão'])assert.ok(t.includes(field),field);assert.ok(!/Domínios de deformação|Equilíbrio da seção|estado-atual|barra-longitudinal/.test(s));assert.ok(!/\d,\d{3}/.test(linhas(s)));assert.ok(!/NaN|undefined|Infinity/.test(t));});
test('RV08: dimensionamento reverifica a armadura mínima adotada',()=>{let d=F.dimensionar({...base,Msd:.05}),copy=JSON.stringify(d),a=R.avaliarFlexao(d,op),expected=V.verificar({...base,Msd:.05,As:d.As,Asl:d.Asl});assert.ok(d.As>d.asCalc);assert.equal(a.resultado.MRdTfm,expected.MRdTfm);assert.ok(a.fs>1);assert.notEqual(a.resultado.MRdTfm,d.MRdTfm);assert.equal(JSON.stringify(d),copy);});
test('RV08: capacidade sem demanda não inventa D/C, FS ou aprovação',()=>{let r=F.verificar(base),a=R.avaliarFlexao(r,op),t=clean(R.flexao(r,op));assert.equal(a.dc,null);assert.equal(a.fs,null);assert.ok(t.includes('Sem demanda'));assert.ok(!t.includes('ATENDE'));});
test('RV08: zero, capacidade nula e inconclusivo possuem semântica própria',()=>{assert.deepEqual(R.indices(0,4),{dc:0,fs:null});assert.deepEqual(R.indices(0,0),{dc:null,fs:null});assert.deepEqual(R.indices(4,0),{dc:Infinity,fs:0});assert.deepEqual(R.indices(2,4,'INCONCLUSIVO'),{dc:null,fs:null});assert.deepEqual(R.indices(NaN,4),{dc:null,fs:null});});
test('RV08: excesso real não é encoberto pelo D/C arredondado',()=>{let cap=V.verificar(base).MRdTfm,a=R.avaliarFlexao(V.verificar({...base,Msd:cap*(1+1e-6)}),op);assert.equal(a.situacao,'NÃO ATENDE');assert.ok(a.dc>1);assert.ok(a.fs<1);});
test('RV08: FS de resistência não encobre mínimo ou ductilidade desfavoráveis',()=>{let a=R.avaliarFlexao(V.verificar({...base,As:1,Msd:.01}),op);assert.ok(a.fs>1);assert.equal(a.situacao,'NÃO ATENDE');assert.equal(a.governante,'Armadura mínima');});
test('RV08: resumo do caso retangular mantém proporção horizontal',()=>{let s=R.flexao(V.verificar(base),op),h=+s.match(/height="(\d+)"/)[1];assert.ok(h>=600&&h<=800,h);assert.ok(h<1000);});
test('RV08: identificador é escapado e não suprime avisos',()=>{let r=V.verificar({...base,As:1000}),t=R.flexao(r,{...op,elemento:'<script>alert(1)</script>'});assert.ok(t.includes('&lt;script&gt;'));assert.ok(!t.includes('<script>'));assert.ok(t.includes('NÃO ATENDE'));});
test('RV08: cortante/torção apresenta índices por critério e Asl pendente',()=>{let r=C.calcular({modo:'AMBOS',operacao:'verificar',fck:30,fyk:500,gammaC:1.4,gammaS:1.15,gammaF:1.4,bw:40,bwMin:40,h:50,d:47.5,c1:2.5,modelo:'I',theta:45,alpha:90,refMin:'bw/2',Vsd:7,Tsd:6.96,diamEstribo:10,nRamos:2,sAdotado:8,aslEf:NaN}),t=clean(R.cisalhamento(r,{unidade:'kgf'}));assert.ok(t.includes('PENDENTE'));assert.ok(t.includes('FS'));assert.ok(t.includes('não informada'));assert.ok(!/NaN|undefined/.test(t));});

test('RV08: diagrama MRd × As reavalia o motor sem alterar o resultado nem a entrada',()=>{let r=F.dimensionar({...base,Msd:3.22,bw:20,d:45,dl:4,h:49}),copy=JSON.stringify(r),s=R.flexao(r,op),t=clean(s),a=R.avaliarFlexao(r,op);assert.equal(JSON.stringify(r),copy);assert.ok(Number.isFinite(a.resultado.MRdTfm));assert.ok(t.includes('Diagrama MRd × As'));assert.ok(t.includes('As adotada'));assert.ok(t.includes('As (cm²)'));assert.ok(!/NaN|undefined|Infinity/.test(t));assert.ok(!/\d,\d{3}/.test(linhas(s)));});
test('RV08: seção T traz bf, hf, bw e o desenho da mesa; sem valores inválidos',()=>{let r=V.verificar({...base,secao:'T',bw:20,bf:80,hf:10,h:60,d:55,dl:5,Msd:6,As:4.91}),t=clean(R.flexao(r,{...op,modoAs:'area'}));for(let f of ['bf','hf','bw','Seção T'])assert.ok(t.includes(f),f);assert.ok(!/NaN|undefined|Infinity/.test(t));});
test('RV08: capacidade não inventa demanda nem aprovação no resumo e no diagrama',()=>{let r=F.verificar({...base,As:3}),s=R.flexao(r,{...op,modoAs:'area'}),t=clean(s);assert.ok(t.includes('CAPACIDADE'));assert.ok(t.includes('Sem demanda'));assert.ok(!t.includes('ATENDE'));assert.ok(!/NaN|undefined|Infinity/.test(t));assert.ok(!/stroke-dasharray="5 3"/.test(s));});
test('RV08: casos extremos (laje, dupla, kN·m, NÃO ATENDE) geram SVG íntegro',()=>{let casos=[{...base,Msd:9.5,Asl:0},{...base,As:1000},{...base,Msd:0}];for(let c of casos){let s=R.flexao(V.verificar(c),{...op,unidade:'knm',modoAs:'area'}),t=clean(s);assert.ok(/^<svg[\s\S]*<\/svg>$/.test(s));assert.ok(!/NaN|undefined/.test(t),JSON.stringify(c));}});
const cb={modo:'AMBOS',operacao:'verificar',fck:30,fyk:500,gammaC:1.4,gammaS:1.15,gammaF:1.4,bw:40,bwMin:40,h:50,d:47.5,c1:2.5,modelo:'I',theta:45,alpha:90,refMin:'bw/2',Vsd:7,Tsd:6.96,diamEstribo:10,nRamos:2,sAdotado:8,aslEf:NaN};
test('RV08: cortante/torção em três painéis traz seção, dados, diagrama, esforços e verificações',()=>{let r=C.calcular(cb),copy=JSON.stringify(r),s=R.cisalhamento(r,{unidade:'tf',norma:'2023',elemento:'V7 <x>'}),t=clean(s);assert.equal(JSON.stringify(r),copy);assert.ok(s.includes('&lt;x&gt;'));
for(let f of ['Seção transversal','Dados e resultados','Estribos × espaçamento','Esforços','Solução adotada','Verificações','Critério','Demanda','Capacidade','D/C','FS','Utilização','Situação','Conclusão','fck','fyk','fywd','bw,mín','Ae','Asl','não informada','PENDENTE','Seção vazada','smáx','sadotado'])assert.ok(t.includes(f),f);
assert.ok(!/NaN|undefined|Infinity/.test(t));assert.ok(!/\d,\d{3}/.test(linhas(s)));assert.ok(/^<svg[\s\S]*<\/svg>$/.test(s));});
test('RV08: cortante apenas não traz torção; torção apenas não traz cortante',()=>{let v=clean(R.cisalhamento(C.calcular({...cb,modo:'CORTANTE',Vsd:10}),{unidade:'kgf'})),k=clean(R.cisalhamento(C.calcular({...cb,modo:'TORCAO',Tsd:3,aslEf:10}),{unidade:'kn'}));
assert.ok(v.includes('Cortante'));assert.ok(!v.includes('Seção vazada'));assert.ok(!v.includes('Asl'));assert.ok(v.includes('kgf'));assert.ok(!v.includes('Biela · torção'));
assert.ok(k.includes('Seção vazada'));assert.ok(k.includes('Asl,nec'));assert.ok(k.includes('kN·m'));assert.ok(!k.includes('Biela · cortante'));assert.ok(!k.includes('não informada'));});
test('RV08: índices do resumo de cortante/torção coincidem com o motor e com aprovação por critério',()=>{let r=C.calcular({...cb,aslEf:10}),t=clean(R.cisalhamento(r,{unidade:'tf'})),tr=r.verificacoes.find(v=>v.id==='transversal');assert.ok(t.includes(tr.razao.toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2})));
let ruim=C.calcular({...cb,aslEf:10,sAdotado:20}),s=R.cisalhamento(ruim,{unidade:'tf'});assert.equal(ruim.atendimento,'NÃO ATENDE');assert.ok(clean(s).includes('NÃO ATENDE'));assert.ok(clean(s).includes('Conclusão: NÃO ATENDE'));});
test('RV08: cortante/torção — casos extremos geram SVG íntegro',()=>{let casos=[{...cb,Vsd:0,Tsd:0,aslEf:0},{...cb,modo:'CORTANTE',Vsd:200,sAdotado:3},{...cb,modelo:'II',theta:30,modo:'CORTANTE',Vsd:30},{...cb,sAdotado:1.5,aslEf:100}];for(let e of casos){let s=R.cisalhamento(C.calcular(e),{unidade:'kgf'}),x=clean(s);assert.ok(/^<svg[\s\S]*<\/svg>$/.test(s));assert.ok(!/NaN|undefined/.test(x),JSON.stringify(e));}});
test('RV08: números de 7 dígitos em kgf reduzem a fonte da tabela de esforços em vez de invadir a célula vizinha',()=>{
const tam=(s,txt)=>{let m=s.match(new RegExp('font-size="([\\d.]+)"[^>]*>'+txt.replace(/\./g,'\\.')+'<'));return m?+m[1]:null;};
let grande=R.cisalhamento(C.calcular({...cb,bw:150,bwMin:150,h:250,d:240,c1:8,Vsd:2500,Tsd:300,diamEstribo:20,nRamos:6,sAdotado:6,aslEf:120}),{unidade:'kgf'}),normal=R.cisalhamento(C.calcular(cb),{unidade:'tf'});
let f=tam(grande,'2.500.000,00');assert.ok(f!==null&&f>=10&&f<18,String(f));assert.ok(/font-size="18"[^>]*>\d+,\d\d</.test(normal));assert.ok(!/NaN|undefined/.test(clean(grande)));});
test('RV08: margem do diagrama acompanha os números do eixo vertical, sem encostar no título do eixo',()=>{
const plotX=s=>+s.match(/<rect x="([\d.]+)" y="[\d.]+" width="[\d.]+" height="[\d.]+" fill="#FFFBEC"/)[1];
let n=R.flexao(V.verificar({...base,As:6}),{...op,unidade:'tfm',modoAs:'area'}),g=R.flexao(V.verificar({...base,secao:'T',bw:80,bf:350,hf:30,h:250,d:235,dl:6,Msd:3500,As:420}),{...op,unidade:'kgfm',modoAs:'area'});
assert.equal(plotX(n),752);assert.ok(plotX(g)>plotX(n),String(plotX(g)));assert.ok(!/NaN|undefined|Infinity/.test(clean(g)));});
