'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const scope={};
for(const name of ['norma','flexao','entrada-flexao','verificacao-flexao','painel-flexao'])new Function('globalThis',fs.readFileSync(path.join(__dirname,'../js',name+'.js'),'utf8'))(scope);
const {Flexao:F,PainelFlexao:P,VerificacaoFlexao:V}=scope.FS;
const base={fck:30,fyk:500,tipoAco:'A',gammaC:1.4,gammaS:1.15,gammaF:1.4,secao:'RET',bw:20,d:45,dl:4,Msd:3.22,armaduraDupla:true,usarArmaduraMinima:true};
const opt={documento:true,elemento:'PAREDES E FUNDOS CAIXA TRAVESSIA TQ 140.22',usarMin:true};
const clean=s=>s.replace(/<\/text>/g,' ').replace(/<[^>]*>/g,'').replace(/&gt;/g,'>').replace(/&lt;/g,'<').replace(/&amp;/g,'&').replace(/\s+/g,' ');
for(const values of [[3,2,1],[3,1,2],[2,3,1],[2,1,3],[1,3,2],[1,2,3]])test('RV02: ordem decrescente '+values,()=>{let q=P.ordenarAreas({modo:'MSD_AS',As:values[0],asCalc:values[1],asMin:values[2]});assert.deepEqual(q.itens.map(a=>a.valor),[3,2,1]);assert.deepEqual(q.operadores,['>','>']);});
test('RV02: empate real e estável; exemplo enviado',()=>{let r=F.dimensionar(base);assert.equal(P.compareAreas(r),'As,adotada = As,calc > As,mín');});
test('RV02: mínima governa muda posição, não orientação',()=>{let r=F.dimensionar({...base,Msd:.1});assert.equal(P.compareAreas(r),'As,adotada = As,mín > As,calc');});
test('RV02: três valores iguais mantêm prioridade sem inventar >',()=>{let q=P.ordenarAreas({modo:'MSD_AS',As:2,asCalc:2,asMin:2});assert.equal(q.texto,'As,adotada = As,calc = As,mín');});
test('RV02: arredondamento não cria igualdade matemática',()=>{let q=P.ordenarAreas({modo:'MSD_AS',As:1.6841,asCalc:1.6801,asMin:1.47});assert.equal(q.texto,'As,adotada > As,calc > As,mín');assert.equal(q.casas,2);});
test('RV02: valores ausentes não equivalem a zero',()=>{let q=P.ordenarAreas({modo:'MSD_AS',As:NaN,asCalc:1,asMin:2});assert.equal(q.texto,'Comparação indisponível');});
test('RV02: capacidade não fabrica As calculada nem aprovação',()=>{let r=F.verificar({...base,As:2,Asl:0}),s=clean(P.montar(r,opt));assert.ok(!s.includes('As,calc'));assert.ok(s.includes('Sem demanda independente'));assert.ok(!s.includes('ATENDE'));});
test('RV02: verificação preserva demanda, capacidade e quatro critérios',()=>{let r=V.verificar({...base,Msd:20,As:2,Asl:0}),s=clean(P.montar(r,opt));assert.ok(s.includes('Armadura adotada × momento solicitante'));assert.ok(s.includes('20,00 tf·m'));assert.ok(s.includes('MRd'));assert.ok(s.includes('NÃO ATENDE'));assert.ok(!s.includes('As,calc'));for(let v of r.verificacoes)assert.ok(s.includes(v.titulo)&&s.includes(v.situacao));});
test('RV02: aviso do estado antes da mínima permanece contíguo aos modelos',()=>{let r=F.dimensionar({...base,Msd:.1}),s=clean(P.montar(r,opt));assert.ok(s.indexOf('Estado antes da mínima')<s.indexOf('Domínios de deformação'));assert.ok(s.includes('D/C e FS do resumo reverificam'));});
test('RV02: zero não aparece como mínima governante',()=>{let s=clean(P.montar(F.dimensionar({...base,Msd:0}),opt));assert.ok(s.includes('Momento nulo; mínima não adotada pelo motor.'));});
test('RV02: composição compacta preserva corpo físico e todos os campos',()=>{let r=F.dimensionar(base),s=P.montar(r,opt),t=clean(s);assert.match(s,/font-size="18.5"/);for(let name of ['fck','fyk','fctk,sup','γc','γs','αc','λ','Msk','MSd','γf','As,calc','As,mín','As,adotada','As,máx','Ac','ρmín','Md,mín','εs','εc','εyd','εc2','βx,lim','Rt,eq'])assert.ok(t.includes(name),name);assert.ok(+/height="(\d+)"/.exec(s)[1]<1200);});
test('RV02: opção ampliada permanece disponível, sem modificar o estado',()=>{let r=F.dimensionar(base),copy=JSON.stringify(r),a=P.montar(r,opt),b=P.montar(r,{...opt,composicao:'ampliada'});assert.ok(+/height="(\d+)"/.exec(a)[1]<+/height="(\d+)"/.exec(b)[1]);assert.equal(JSON.stringify(r),copy);});
test('RV02: cor não é a única indicação de não atendimento',()=>{let r=V.verificar({...base,Msd:20,As:2,Asl:0}),s=P.montar(r,opt);assert.ok(s.includes('#B42318'));assert.ok(s.includes('NÃO ATENDE'));});
